### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bwreid** [hardr/skys_the_limit#1]
🗼 
- Your HTML isn't valid, sadly. 
- [index.html, L7](https://github.com/hardr/skys_the_limit/blob/master/index.html#L7): If you're going to comment out code/markup, I would remove it before committing.
- [index.html, L14-26](https://github.com/hardr/skys_the_limit/blob/master/index.html#L14-L26): Be careful with indentation!
- [index.html, L28-34](https://github.com/hardr/skys_the_limit/blob/master/index.html#L28-L34): If you remove this image everything below floats up to replace it. Review `clear: both;` in order to fix this!
- [index.html, L36](https://github.com/hardr/skys_the_limit/blob/master/index.html#L36): `jpeg` is not really a great name for a folder... what about `images`?
- [index.html, L42](https://github.com/hardr/skys_the_limit/blob/master/index.html#L42): I wouldn't use the `align` attribute when you can use CSS.
- [index.html, L59](https://github.com/hardr/skys_the_limit/blob/master/index.html#L59): If you don't want a link to go anywhere, I would do `href="#"`.
- [main.css, L134](https://github.com/hardr/skys_the_limit/blob/master/styles/main.css#L134): This will, sadly, not do what you want. It has no effect right now.

Really nice job on the CSS. Make sure to review `float` and `clear` before moving forward. Make the above changes and re-push to github!

**Comment by ryanHarings** [comment]
Done!

**Comment by ryanHarings** [comment]
Thanks, dude!
